-- PROGRESSION - 1


-- 1. **Create table city**

CREATE TABLE CITY (
    CITY_ID INT NOT NULL,
    CITY_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(CITY_ID)
); 

-- 2. **Create table referee**
CREATE TABLE REFEREE (
    REFEREE_ID INT NOT NULL,
    REFEREE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(REFEREE_ID)
); 


-- 3. **Create table innings**
CREATE TABLE INNINGS (
    INNINGS_ID INT NOT NULL,
    INNINGS_NUMBER INT NOT NULL,
    PRIMARY KEY(INNINGS_ID)
); 


-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE (
    EXTRA_TYPE_ID INT NOT NULL,
    EXTRA_TYPE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(EXTRA_TYPE_ID)
); 


-- 5. **Create table skill**
CREATE TABLE SKILL (
    SKILL_ID INT NOT NULL,
    SKILL_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(SKILL_ID)
); 

-- 6. **Create table team**
CREATE TABLE TEAM (
    TEAM_ID INT NOT NULL,
    TEAM_NAME VARCHAR(50) NOT NULL,
    COACH VARCHAR(50) NOT NULL,
    HOME_CITY INT NOT NULL,
    CAPTAIN INT NOT NULL,   
    PRIMARY KEY(TEAM_ID),
    FOREIGN KEY (HOME_CITY) REFERENCES CITY(CITY_ID)
);

-- 7. **Create table player**
CREATE TABLE PLAYER 
(
    PLAYER_ID INT NOT NULL,
    PLAYER_NAME VARCHAR(50) NOT NULL,
    PLAYER_COUNTRY VARCHAR(50) NOT NULL,
    SKILL_ID INT NOT NULL,  
    TEAM_ID INT NOT NULL, 
    PRIMARY KEY(PLAYER_ID),
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

-- 8. **Create table venue**
CREATE TABLE VENUE 
(
    VENUE_ID INT NOT NULL,
    STADIUM_NAME VARCHAR(50) NOT NULL,
    CITY_ID INT NOT NULL,
    PRIMARY KEY(VENUE_ID),
    FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
    
);

-- 9. **Create table event**
CREATE TABLE EVENT
(
 	EVENT_ID INT NOT NULL PRIMARY KEY,
 	INNINGS_ID INT NOT NULL,
 	EVENT_NO INT NOT NULL,
 	RAIDER_ID INT NOT NULL,
 	RAID_POINTS INT NOT NULL,
 	DEFENDING_POINTS INT NOT NULL,
 	CLOCK_IN_SEC INT NOT NULL,
 	TEAM_1_SCORE INT NOT NULL,
 	TEAM_2_SCORE INT NOT NULL,
 	FOREIGN KEY (INNINGS_ID) REFERENCES INNINGS(INNINGS_ID),
 	FOREIGN KEY (RAIDER_ID) REFERENCES PLAYER(PLAYER_ID)

);
-- 10. **Create table extra_event**.
CREATE TABLE EXTRA_EVENT
(
 	EXTRA_EVENT_ID INT NOT NULL PRIMARY KEY,
 	EVENT_ID INT NOT NULL,
 	EXTRA_TYPE_ID INT NOT NULL,
 	POINTS INT NOT NULL,
 	SCORING_TEAM_ID INT NOT NULL,
 	FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
 	FOREIGN KEY (EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(EXTRA_TYPE_ID),
 	FOREIGN KEY (SCORING_TEAM_ID) REFERENCES TEAM(TEAM_ID)

);

-- 11. **Create table outcome**
CREATE TABLE OUTCOME
(
	OUTCOME_ID INT NOT NULL PRIMARY KEY,
	STATUS VARCHAR(100) NOT NULL,
	WINNER_TEAM_ID INT,
	SCORE INT,
	PLAYER_OF_MATCH INT,
	FOREIGN KEY (WINNER_TEAM_ID) REFERENCES TEAM(TEAM_ID),
 	FOREIGN KEY (PLAYER_OF_MATCH) REFERENCES PLAYER(PLAYER_ID)


);

-- 12. **Create table game**

CREATE TABLE GAME
(
	GAME_ID INT NOT NULL PRIMARY KEY,
	GAME_DATE DATE NOT NULL,
	TEAM_ID_1 INT NOT NULL,
	TEAM_ID_2 INT NOT NULL,
	VENUE_ID INT NOT NULL,
	OUTCOME_ID INT NOT NULL,
	REFEREE_ID_1 INT NOT NULL,
	REFEREE_ID_2 INT NOT NULL,
	FIRST_INNINGS_ID INT NOT NULL,
	SECOND_INNINGS_ID INT NOT NULL,	
	FOREIGN KEY (TEAM_ID_1) REFERENCES TEAM(TEAM_ID),
	FOREIGN KEY (TEAM_ID_2) REFERENCES TEAM(TEAM_ID),
	FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID),
	FOREIGN KEY (OUTCOME_ID) REFERENCES OUTCOME(OUTCOME_ID),
	FOREIGN KEY (REFEREE_ID_1) REFERENCES REFEREE(REFEREE_ID),
	FOREIGN KEY (REFEREE_ID_1) REFERENCES REFEREE(REFEREE_ID),
	FOREIGN KEY (FIRST_INNINGS_ID) REFERENCES INNINGS(INNINGS_ID),
	FOREIGN KEY (SECOND_INNINGS_ID) REFERENCES INNINGS(INNINGS_ID)
	

);

-- 13. **Drop table city**
DROP TABLE CITY;

-- 14. **Drop table innings**
DROP TABLE INNINGS;

-- 15. **Drop table skill**
DROP TABLE SKILL;

-- 16. **Drop table extra_type**
DROP TABLE EXTRA_TYPE;
